export const employees = [
    {
        id: 1,
        name: "Dr. Sarah Smith",
        role: "Chief Medical Officer",
        img: "https://i.pravatar.cc/150?u=1",
        email: "sarah.smith@hospital.com",
        phone: "+91 98765 43210",
        city: "Mumbai, India",
        department: "Cardiology",
        joinDate: "15 Jan 2020",
        bio: "Experienced cardiologist with over 15 years of practice in top hospitals."
    },
    {
        id: 2,
        name: "James Wilson",
        role: "Senior Surgeon",
        img: "https://i.pravatar.cc/150?u=2",
        email: "james.wilson@hospital.com",
        phone: "+91 98765 43211",
        city: "Delhi, India",
        department: "Surgery",
        joinDate: "22 Mar 2019",
        bio: "Specialist in minimally invasive surgical procedures."
    },
    {
        id: 3,
        name: "Emily Davis",
        role: "Head Nurse",
        img: "https://i.pravatar.cc/150?u=3",
        email: "emily.davis@hospital.com",
        phone: "+91 98765 43212",
        city: "Bangalore, India",
        department: "Nursing",
        joinDate: "10 Feb 2021",
        bio: "Dedicated nursing professional ensuring top-quality patient care."
    },
    {
        id: 4,
        name: "Michael Brown",
        role: "Hospital Administrator",
        img: "https://i.pravatar.cc/150?u=4",
        email: "michael.brown@hospital.com",
        phone: "+91 98765 43213",
        city: "Pune, India",
        department: "Administration",
        joinDate: "05 Nov 2018",
        bio: "Efficient administrator managing hospital operations and logistics."
    },
    {
        id: 5,
        name: "Noah Williams",
        role: "Finance Head",
        img: "https://i.pravatar.cc/150?u=5",
        email: "noah.w@hospital.com",
        phone: "+91 98765 43214",
        city: "Hyderabad, India",
        department: "Finance",
        joinDate: "12 Dec 2020",
        bio: "Financial expert handling hospital budgeting and accounts."
    },
    {
        id: 6,
        name: "Isabella Rossi",
        role: "Operations Manager",
        img: "https://i.pravatar.cc/150?u=6",
        email: "isabella.r@hospital.com",
        phone: "+91 98765 43215",
        city: "Chennai, India",
        department: "Operations",
        joinDate: "08 Aug 2021",
        bio: "Operational lead focusing on process optimization."
    },
    {
        id: 7,
        name: "Ava Thompson",
        role: "HR Executive",
        img: "https://i.pravatar.cc/150?u=7",
        email: "ava.t@hospital.com",
        phone: "+91 98765 43216",
        city: "Kolkata, India",
        department: "HR",
        joinDate: "20 May 2022",
        bio: "HR professional dedicated to talent acquisition and management."
    },
    {
        id: 8,
        name: "Liam Carter",
        role: "Product Designer",
        img: "https://i.pravatar.cc/150?u=8",
        email: "liam.c@hospital.com",
        phone: "+91 98765 43217",
        city: "Ahmedabad, India",
        department: "IT",
        joinDate: "14 Jun 2021",
        bio: "UX/UI expert creating seamless digital experiences."
    },
    {
        id: 9,
        name: "Grace Kim",
        role: "Customer Lead",
        img: "https://i.pravatar.cc/150?u=9",
        email: "grace.k@hospital.com",
        phone: "+91 98765 43218",
        city: "Surat, India",
        department: "Support",
        joinDate: "30 Sep 2019",
        bio: "Customer success lead focusing on patient satisfaction."
    },
    {
        id: 10,
        name: "Ethan Lee",
        role: "IT Specialist",
        img: "https://i.pravatar.cc/150?u=10",
        email: "ethan.l@hospital.com",
        phone: "+91 98765 43219",
        city: "Jaipur, India",
        department: "IT",
        joinDate: "11 Nov 2020",
        bio: "Systems specialist managing digital infrastructure."
    },
    {
        id: 11,
        name: "Emily Baker",
        role: "Marketing Manager",
        img: "https://i.pravatar.cc/150?u=11",
        email: "emily.b@hospital.com",
        phone: "+91 98765 43220",
        city: "Lucknow, India",
        department: "Marketing",
        joinDate: "05 Apr 2021",
        bio: "Growth specialist driving hospital brand awareness."
    },
    {
        id: 12,
        name: "Micheal Shaun",
        role: "Sales Director",
        img: "https://i.pravatar.cc/150?u=12",
        email: "micheal.s@hospital.com",
        phone: "+91 98765 43221",
        city: "Kanpur, India",
        department: "Sales",
        joinDate: "18 Jul 2018",
        bio: "Experienced sales leader with a focus on partnerships."
    },
    {
        id: 13,
        name: "Sophia Martinez",
        role: "Junior Doctor",
        img: "https://i.pravatar.cc/150?u=13",
        email: "sophia.m@hospital.com",
        phone: "+91 98765 43222",
        city: "Nagpur, India",
        department: "Cardiology",
        joinDate: "01 Feb 2023",
        bio: "Rising medical professional with a focus on cardiac care."
    },
    {
        id: 14,
        name: "Jackson White",
        role: "Nurse Practitioner",
        img: "https://i.pravatar.cc/150?u=14",
        email: "jackson.w@hospital.com",
        phone: "+91 98765 43223",
        city: "Indore, India",
        department: "Emergency",
        joinDate: "15 Oct 2021",
        bio: "Emergency care specialist with high-pressure experience."
    },
    {
        id: 15,
        name: "Lucas Garcia",
        role: "Pathologist",
        img: "https://i.pravatar.cc/150?u=15",
        email: "lucas.g@hospital.com",
        phone: "+91 98765 43224",
        city: "Thane, India",
        department: "Lab",
        joinDate: "20 Dec 2019",
        bio: "Laboratory expert specializing in disease diagnosis."
    },
    {
        id: 16,
        name: "Mia Robinson",
        role: "Radiologist",
        img: "https://i.pravatar.cc/150?u=16",
        email: "mia.r@hospital.com",
        phone: "+91 98765 43225",
        city: "Bhopal, India",
        department: "Radiology",
        joinDate: "12 May 2020",
        bio: "Imaging specialist with expertise in MRI and CT scans."
    },
    {
        id: 17,
        name: "Oliver Nelson",
        role: "Pharmacist",
        img: "https://i.pravatar.cc/150?u=17",
        email: "oliver.n@hospital.com",
        phone: "+91 98765 43226",
        city: "Visakhapatnam, India",
        department: "Pharmacy",
        joinDate: "25 Sep 2021",
        bio: "Medication expert ensuring safe and effective drug use."
    },
    {
        id: 18,
        name: "Amelia King",
        role: "Receptionist",
        img: "https://i.pravatar.cc/150?u=18",
        email: "amelia.k@hospital.com",
        phone: "+91 98765 43227",
        city: "Patna, India",
        department: "Front Desk",
        joinDate: "10 Mar 2022",
        bio: "Front desk professional providing excellent patient coordination."
    },
    {
        id: 19,
        name: "Harper Green",
        role: "Security Head",
        img: "https://i.pravatar.cc/150?u=19",
        email: "harper.g@hospital.com",
        phone: "+91 98765 43228",
        city: "Vadodara, India",
        department: "Security",
        joinDate: "05 Jun 2019",
        bio: "Security expert ensuring safety across hospital premises."
    },
    {
        id: 20,
        name: "Evelyn Adams",
        role: "Librarian",
        img: "https://i.pravatar.cc/150?u=20",
        email: "evelyn.a@hospital.com",
        phone: "+91 98765 43229",
        city: "Ghaziabad, India",
        department: "Education",
        joinDate: "15 Nov 2020",
        bio: "Medical knowledge curator for staff and students."
    },
    {
        id: 21,
        name: "Abigail Hill",
        role: "Dietician",
        img: "https://i.pravatar.cc/150?u=21",
        email: "abigail.h@hospital.com",
        phone: "+91 98765 43230",
        city: "Ludhiana, India",
        department: "Nutrition",
        joinDate: "22 Jan 2021",
        bio: "Nutrition specialist creating personalized patient diets."
    },
    {
        id: 22,
        name: "Ella Baker",
        role: "Physiotherapist",
        img: "https://i.pravatar.cc/150?u=22",
        email: "ella.b@hospital.com",
        phone: "+91 98765 43231",
        city: "Agra, India",
        department: "Rehabilitation",
        joinDate: "30 Apr 2019",
        bio: "Rehab specialist focusing on physical recovery."
    },
    {
        id: 23,
        name: "Scarlett Scott",
        role: "Social Worker",
        img: "https://i.pravatar.cc/150?u=23",
        email: "scarlett.s@hospital.com",
        phone: "+91 98765 43232",
        city: "Nashik, India",
        department: "Public Health",
        joinDate: "12 Aug 2022",
        bio: "Community health worker dedicated to social support."
    },
    {
        id: 24,
        name: "Victoria Cook",
        role: "Anesthesiologist",
        img: "https://i.pravatar.cc/150?u=24",
        email: "victoria.c@hospital.com",
        phone: "+91 98765 43233",
        city: "Faridabad, India",
        department: "Surgery",
        joinDate: "18 Dec 2018",
        bio: "Critical care specialist managing anesthesia in surgeries."
    },
    {
        id: 25,
        name: "Madison Evans",
        role: "Pediatrician",
        img: "https://i.pravatar.cc/150?u=25",
        email: "madison.e@hospital.com",
        phone: "+91 98765 43234",
        city: "Meerut, India",
        department: "Pediatrics",
        joinDate: "01 Jul 2020",
        bio: "Child healthcare expert with a focus on neonatology."
    }
];
